### ISSUE TITLE
CMake Error at CMakeLists.txt:175 (INSTALL)

### ISSUE THREAD

**Issue by zapplelove** [ORB-HD/rbdl-toolkit#11]
cmake -DCUSTOM_QT_PATH=~/Qt/5.14.2/gcc_64 ..
```bash
-- Found RBDL: /usr/local/lib/librbdl.so
-- Found RBDL LUAMODEL: /usr/local/lib/librbdl_luamodel.so
-- Boost version: 1.65.1
CMake Error at CMakeLists.txt:175 (INSTALL):
  INSTALL TARGETS given no LIBRARY DESTINATION for shared library target
  "toolkitlib".


-- Configuring incomplete, errors occurred!
See also "~/Src/dynamicTools/rbdl-toolkit/build/CMakeFiles/CMakeOutput.log".
```

**Comment by zapplelove** [comment]
When I use the `rbdl-toolkit-x86_64.appimage`, program no response

**Comment by zapplelove** [comment]
> ```shell
> CMake Error at CMakeLists.txt:175 (INSTALL):
>   INSTALL TARGETS given no LIBRARY DESTINATION for shared library target
>   "toolkitlib".
> ```

change the line 175 of the [CMakeLists.txt](https://github.com/ORB-HD/rbdl-toolkit/blob/master/CMakeLists.txt) file to `INSTALL ( TARGETS toolkitlib RUNTIME DESTINATION lib LIBRARY DESTINATION lib)` will solve this problem.

**Comment by ju6ge** [comment]
as of the newest commit on master the cmake error is fixed
