### ISSUE TITLE
Model documentation

### ISSUE THREAD

**Issue by jfslin** [ORB-HD/rbdl-toolkit#18]
I've started some model [documentation](https://github.com/ORB-HD/rbdl-toolkit/wiki/Creating-Models) but I think someone will need to fill in same of the gaps. 

@ju6ge do you have a working Lua and/or URDF model that only has 2-3 links so it's to read? I took the prosthesis model you sent me and cropped out only the right arm. It loads okay, so we could probably stick with that if needed.

**Comment by ju6ge** [comment]
Hey yes I do have some simpler models. 

[simplemodels.tar.gz](https://github.com/ORB-HD/rbdl-toolkit/files/5933510/simplemodels.tar.gz)
