### ISSUE TITLE
Inverse dynamics

### ISSUE THREAD

**Issue by jfslin** [ORB-HD/rbdl-toolkit#28]
Is there inverse dynamics functionality in toolkit?

**Comment by ju6ge** [comment]
As of yet there is no plugin to do that computation.

**Comment by ju6ge** [comment]
The RBDL library,has functions for computing forward and inverse dynamics, it would just be a matter of writing a plugin to read the animation frames values to get the joint positions, then calculate the joint velocities and accelerations and then calling the InverseDynamics rbdl function to get the actuations of the internal joints. They could them be visualized with the force/torque model extension.

**Comment by jfslin** [comment]
I spoke to Katja about this and she's pretty against just doing numerical diff to get velo/accel and then using that to ID. This will be a bit of a bigger project to handle. I'll close this for now, and will have to come back to it later.
