### ISSUE TITLE
Building on Linux system

### ISSUE THREAD

**Issue by nag92** [ORB-HD/rbdl-toolkit#34]
Hello,

I am having trouble building the package on my linux system. I followed the install instructions for Qt5 but I dont seem to have anything close to the path ~/Qt5.13/5.13.2/gcc_64

I have built and compiled QT5.15 with a parallel build folder. so I have the following folders

qt5/
qt5-build/

which were created by following the install instructions linked in your wiki. (https://wiki.qt.io/Building_Qt_5_from_Git#Getting_the_source_code) 
What am I doing wrong?

**Comment by ju6ge** [comment]
Hey, I would not recommend building Qt yourself. I have done that for testing purposes but it is far easier to just use the [online installer](https://www.qt.io/download-qt-installer?utm_referrer=https%3A%2F%2Fwww.qt.io%2Fdownload-open-source). It will create the folder structure used in the tutorial if my memory serves me correctly. When you use the self build version of qt the correct path should be the install folder. I am not quite sure if that is the same as the build folder or if it is created with another command. Anyway when using self build qt you really need to make sure that all dependencies are present and the correct options are set in the build environment in order for all components to be present. So I definitely recommend you switch to using the installer!

Are you planning on developing add functionality to the toolkit? If you just want to use the toolkit it should be far easier to just use the [appimage](https://github.com/ORB-HD/rbdl-toolkit/releases/latest/download/rbdl-toolkit-x86_64.AppImage). And even when you only want to build a new addon there is a seperate appimage to build new addons that will work with the main appimage ;)

**Comment by nag92** [comment]
ok, thank you for the clarification, I am way less confused now. I might be writing my own plugin, I need to play around a bit to see what I need. I am using RBDL to build controller for robots in a custom simulation. I want to make sure the RBDL model matches the simulation.  We have a custom parser for our model config files. I was not sure if I needed to build from source to get everything working together.

**Comment by ju6ge** [comment]
RBDL-Toolkit was build with extensibility in mind. Every feature apart from the core code is build as an addon, which can be selectively enabled and disabled ;)

For building Addons that are compatible with the appimage there is [plugin builder](https://github.com/ORB-HD/rbdl-toolkit/releases/download/v1.1.4/toolkit-buildplugin-x86_64.Appimage). There is also a [plugin template](https://github.com/ORB-HD/toolkit-plugin-template). That being said depending on what you plan to do you might need add core functionality. But as long as you stick to the binary version of Qt you should have a way better time getting that running. Best of luck to you ;)

**Comment by nag92** [comment]
@ju6ge I found the problem with the lining error. I have some external code i am using the is compiled against RBDL and I did not recompile it when I updated my local RBDL install.
