### ISSUE TITLE
CMake complains when TOOLKIT_BUILD_OPTIONAL_PLUGINS = On

### ISSUE THREAD

**Issue by mjhmilla** [ORB-HD/rbdl-toolkit#7]
Of course I wanted to try the fancy stuff out : )

When I set "TOOLKIT_BUILD_OPTIONAL_PLUGINS" to "On"

then CMake complains with the message:

----------
 CMake Error at plugins/RenderPlugin/CMakeLists.txt:35 (ADD_SUBDIRECTORY):
   The source directory

     /home/mjhmilla/dev/orbGitHubCode/meshup2020/plugins/RenderPlugin/vendor/QVideoWriter

   does not contain a CMakeLists.txt file.

----------

**Comment by ju6ge** [comment]
This is a problem of with git submodules. To fix the problem you can either clone the project recursively with 
```git clone --recursive``` 
or initialize the sub modules after cloneing with
```git submodule init && git submodule update```

I will add a note to the README to make people aware of the need to recursively clone the repository.
